// export const SERVER_URL = "https://gomuuv-446812.de.r.appspot.com/api";
export const SERVER_URL = "http://192.168.137.1:4200/api";
export const END_POINTS = {
  SIGNUP: `/users`,
  LOGIN: `/users/login`,
  FORGOT_PASSWORD: `/users/forgot-password`,
  UPDATE_USER: `/users/`,
  UPDATE_PROFILE_PICTURE: `/users/profile/update-profile-picture`,
  CHANGE_PASSWORD: "/users/change-password",
  GET_CATEGORIES: `/categories`,
  GET_ALL_PRODUCTS: `/products`,
  ADD_TO_CART: `/cart/add-to-cart`,
  GET_CART: `/cart`,
  REMOVE_FROM_CART: `/cart/remove-from-cart`,
  GOALS: "/goals",
  PLACE_ORDER: `/orders`,
  EXERCISE: "/exercises",
  EXERCISE_COMPLETED: "/workout-sessions/mark-exercise-complete",
  FASTING_PLANS: "/fasting-plans",
  FASTING_HISTORY: "/fasting-history/fasting-stats",
  CURRENT_FASTING: "/fasting-history/current-fast",
  GET_ALL_FASTING_HISTORY: "/fasting-history",
  FASTING_CHART_DATA: "/fasting-history/chart-data",
  END_FASTING_SESSION: "/fasting-history/end-fasting",
  WORKOUTS: "/workouts",
  TRAINER_WORKOUTS: "/workouts/trainer/list",
  EQUIPMENTS_WORKOUTS: "/equipment-workouts",
  UPDATE_EQUIPMENTS_WORKOUTS: "/equipment-workouts/update-day-stats",
  WORKOUT_SESSIONS: "/workout-sessions",
  SESSION_COMPLETED: "/workout-sessions/mark-session-complete",
  PERSONALIZED_PLANS: "/personalized-plans",
  DAILY_PLANS: "/daily-plans",
  ADD_DAILY_PLAN: "/daily-plans/add-meal",
  DIET_PLANS: "/diet-plans",
  NUTRITION_MEALS: "/nutrition-meals",
  PHYSICAL_ACTIVITIES: "/physical-activities",
  ORDERS: "/orders",
  CHALLENGES: "/challenges",
  UPDATE_DAY_STATS: "/challenges/update-day-stats",
  WORKOUTS_UPDATE_DAY_STATS: "/workout-sessions/update-day-stats",
  COMPLETE_CHALLENGE_EXERCISE: "/challenges/complete-exercise",
  ATTACHMENT: "/attachment",
};
